books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, AddReview


app_name = 'books'
urlpatterns = [
    path('<int:id>/', BookDetailView.as_view(), name='detail' ),
    path('<int:id>/reviews/' , AddReview.as_view() , name='reviews') ,
    path('', BookListView.as_view(),  name='list'),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('users/' , include('users.urls' ), name="users"),
    path('' , landing_page, name= "landing_page" ),
    path('home/' , home_page, name= "home" ),
    path('books/' , include('books.urls'), name='books'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

# Create your models here.
# ========= Books table goes here ========
class Books(models.Model):
    title       =models.CharField(max_length=200)
    description =models.TextField()
    isbn        =models.CharField(max_length=13)
    photo       =models.ImageField(upload_to='books/', default='book.png')
    def __str__(self):
        return self.title
    


# ========= Author table goes here ===========
class Author(models.Model):
    first_name  =models.CharField(max_length=200)
    last_name   =models.CharField(max_length=200)
    email       =models.EmailField()
    bio         =models.TextField()
    def __str__(self):
        return self.first_name
    


# ========= BookAuthor table goes here =======
class BookAuthor(models.Model):
    author  =models.ForeignKey(Author, on_delete=models.CASCADE)
    book    =models.ForeignKey(Books, on_delete=models.CASCADE)
    def full_name(self):
        return f"{self.author.first_name} {self.author.last_name}"
# ========= BookReview table goes here =======
class BookReview(models.Model):
    user        =models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book        =models.ForeignKey(Books, on_delete=models.CASCADE)
    comment     =models.TextField()
    stars_given =models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at  =models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f"{self.user.username} rated {self.stars_given} for {self.book.title }"
    

books/forms.py
from django import forms
from .models import Books, BookReview

class ReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('comment' , 'stars_given')

books/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.core.paginator import Paginator
from .models import Books, BookReview
from .forms import ReviewForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

# Create your views here.

class BookListView(LoginRequiredMixin, View):
    def get(self, request):
        books = Books.objects.all().order_by('-id')
        search = request.GET.get('q')
        if search:
            books = Books.objects.filter(title__icontains=search)
        paginator = Paginator(books, 7)
        page = request.GET.get('page', 1)
        pages = paginator.get_page(page)
        return render(request, "books/book-list.html", {"pages":pages})

class BookDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        book = Books.objects.get(id=id)
        form = ReviewForm()
        return render(request, "books/detail.html", {"book":book , "form":form})

class AddReview(LoginRequiredMixin, View):
    def post(self, request, id):
        form = ReviewForm(data=request.POST)
        book = Books.objects.get(id=id)
        if form.is_valid():
            BookReview.objects.create(
                user = request.user,
                book = book,
                comment = form.cleaned_data['comment'],
                stars_given = form.cleaned_data['stars_given']
            )
            return redirect(reverse('books:detail', kwargs={'id':book.id}))
        else:
            return render(request, "books/detail.html", {"book":book , "form":form})

templates/books/book-list.html
{% extends 'base.html' %}
{% block title %} Goodreads | Books {% endblock title %}
{% block additional_styles %}
<style>
    .card img{
        height: 300px;
    }
    @media (max-width: 768px){
        .card img{
            height: 100%;
        }
    }
</style>
{% endblock additional_styles %}
{% block content %}
{% if pages %}
<div class="row mb-2">
    <div class="col-10 col-lg-6 mx-auto">
        <form class="d-flex" role="search" method='get'>
            <input class="form-control me-2 border-info text-info" name='q' type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
    </div>
</div>
    {% for book in pages.object_list %}
    
    <div class="card mb-3 mx-auto">
        <div class="row g-0">
          <div class="col-md-3">
            <img src="{{ book.photo.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-9">
            <div class="card-body">
              <h5 class="card-title"> {{ book.title }} </h5>
              <p class="card-text"> {{ book.description|safe | slice:'300' }}... <a  href="{% url 'books:detail' book.id %}">Read more <i class="fa-solid fa-circle-info read_more_btn"></i></a> </p>
            </div>
          </div>
        </div>
      </div>

    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pages.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1"><i class="fa-solid fa-backward-fast"></i> First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ pages.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link active" style="cursor: not-allowed;"> {{ pages.number }} </a></li>
         {% if pages.has_next %}
         <li class="page-item"><a class="page-link" href="?page={{ pages.next_page_number }}">Next</a></li>
         <li class="page-item"><a class="page-link" href="?page={{ pages.paginator.num_pages }}">Last <i class="fa-solid fa-forward-fast"></i></a></li>
         {% else %}
         <li class="page-item"><a class="page-link disabled">Next </a></li>
         {% endif %}
        </ul>
      </nav>
{% else %}
<p>No books found. <i class="fa-solid fa-folder-open text-info"></i></p>
{% endif %}

{% endblock content %}

templates/books/detail.html
{% extends 'base.html' %}

{% block title %} Goodreads | Book Detail {% endblock title %}
{% load crispy_forms_tags %}
{% block content %}

{% if book %}

<div class="card mb-3 w-85 mx-auto">
    <div class="row g-0">
      <div class="col-md-4">
        <img src=" {{ book.photo.url }} " class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"> {{ book.title }} </h5>
          <p class="text-1">
            {% if book.bookauthor_set.all %}
            Authored by
            {% for author in book.bookauthor_set.all %}
            <strong>{{ author.full_name }}</strong>
            {% endfor %}
            {% else %}
            {% endif %}
          </p>
          <p class="card-text"> {{ book.description|safe }} </p>
          <p class="card-text">ISBN: <small class="text-muted"> {{ book.isbn }} </small></p>
        </div>
      </div>
    </div>
  </div>

  {% if book.bookreview_set.all %}
  <div class="container mt-5 border-left border-right container-comment">
  {% for review in book.bookreview_set.all %}
  <div class="mt-2 justify-content-center py-2">
    <div class="second py-2 px-2"> <span class="text1"> {{ review.comment|safe }} </span>
        <div class="d-flex justify-content-between py-1 pt-2">
            <div><img src="{{ review.user.photo.url }}" width="18"><span class="text2"> {{ review.user.username }} </span></div>
            <div><span class="text3"> {{ review.created_at }} | </span><span class="thumbup"><i class="fa-solid fa-star thumbupo"></i></span><span class="text4"> {{ review.stars_given }} </span></div>
        </div>
    </div>
  {% endfor %}

</div>
  {% endif %}

    <!-- Button trigger modal -->
    <button type="button" title="Leave comment" class="btn btn-primary comment__btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="fa-solid fa-comment"></i>
    </button>

    <!-- Modal -->
    <form action="{% url 'books:reviews' book.id %}" method="post">
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5 font-weight-light" id="exampleModalLabel"><i class="fa-solid fa-bookmark text-info"></i> {{ book.title|slice:"20" }}... </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% csrf_token %}
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Leave comment</button>
        </div>
      </div>
    </div>
  </div>
</form>

{% else %}
<p>not found books</p>
{% endif %}

{% endblock content %}