books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, AddReview


app_name = 'books'
urlpatterns = [
    path('<int:id>/', BookDetailView.as_view(), name='detail' ),
    path('<int:id>/reviews/' , AddReview.as_view() , name='reviews') ,
    path('', BookListView.as_view(),  name='list'),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('users/' , include('users.urls' ), name="users"),
    path('' , landing_page, name= "landing_page" ),
    path('home/' , home_page, name= "home" ),
    path('books/' , include('books.urls'), name='books'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfilePageView, LogoutView, ProfileUpdateView, UsersView


app_name = "users"
urlpatterns = [
    path('register/' , RegisterView.as_view() , name="register"),
    path('login/' , LoginView.as_view() , name='login'),
    path('logout/' , LogoutView.as_view() , name='logout'),
    path( 'profile/update/', ProfileUpdateView.as_view() , name='update' ),
    path('users/' , UsersView.as_view() , name='users'), 
    path('profile/' , ProfilePageView.as_view() , name='profile')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Goodreads {% endblock title %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="{% static 'assets/logo.ico' %}">
    {% block additional_styles %}
    <style>
        body{
            width: 100%;
        }
    </style>
    {% endblock %}
</head>
<body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-info ">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/home/' %}active{% endif %} " aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/books/' %}active{% endif %}" aria-current="page" href="{% url 'books:list' %}">Books</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/users/users/' %}active{% endif %}" aria-current="page" href="{% url 'users:users' %}">Users</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/home/' %}active{% endif %} " aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/books/' %}active{% endif %}" aria-current="page" href="{% url 'books:list' %}">Books</a>
                </li>
                {% endif %}

            </ul>
            {% if request.user.is_authenticated %}
            <div class="btn-group">
                <button type="button" class="btn btn-info text-secondary dropdown-toggle {% if request.path == '/users/profile/' %}active{% endif %}" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ request.user.username }}
                </button>
                <ul class="dropdown-menu dropdown-menu-start dropdown-menu-lg-end">
                  <li><a class="dropdown-item {% if request.path == '/users/profile/' %}active{% endif %}" href="{% url 'users:profile' %}">Profile</a></li>
                  <li><a class="dropdown-item {% if request.path == '/users/profile/update/' %}active{% endif %}" href="{% url 'users:update' %}">Profile Update</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                </ul>
              </div>
              
              {% else %}
              <div class="btn-group">
                <a href="{% url 'users:login' %}" class="btn btn-outline-success">Login</a>
                <a href="{% url 'users:register' %}" class="btn btn-success">Register</a>
              </div>
              {% endif %}
          </div>
        </div>
      </nav>

   <div class="container mt-5 pt-4 pb-2">
    {% block content %}
   </div>
   {% endblock content %}
    {% if messages %}
    {% for message in messages  %}
    <div class="alert alert-{{ message.tags }} alert-message alert-dismissible fade show mt-5" role="alert">
     <i class="fa-solid fa-shield-check"></i> {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
    {% endif %}
   <script src="{% static 'js/app.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} Goodreads | home {% endblock title %}
{% block content %}

{% if pages %}

<div class="row mb-2">
    <div class="col-10 col-lg-6 mx-auto">
        <form class="d-flex" role="search" method='get'>
            <input class="form-control me-2 border-info text-info" name='q' value="{{ search }}" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
    </div>
</div>

<div class="row row-cols-1 row-cols-md-2 g-4">
{% for review in pages.object_list %}
    <div class="col">
      <div class="card bg-transparent border-info p-2">
        <img src="{{ review.user.photo.url }}" class="card-img-top review__img" alt="...">
        <p class="card-title"> <strong>{{ review.user.username }}</strong> rated this book {{ review.stars_given }} <i class="fa-solid fa-star thumbupo"></i> </p>
        <p class="text-1"> {{ review.created_at|date:"d M ,Y | H:i" }} </p>
        <div class="card-body text-info border-info p-1 m-0">
          <p class="card-text text-1"> {{ review.comment }} </p>
          <img src="{{ review.book.photo.url }}" class="card-img-top" alt="...">
        </div>
      </div>
    </div>
{% endfor %}
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination mt-2">
        {% if pages.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1"><i class="fa-solid fa-backward-fast"></i> First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ pages.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link active" style="cursor: not-allowed;"> {{ pages.number }} </a></li>
     {% if pages.has_next %}
     <li class="page-item"><a class="page-link" href="?page={{ pages.next_page_number }}">Next</a></li>
     <li class="page-item"><a class="page-link" href="?page={{ pages.paginator.num_pages }}">Last <i class="fa-solid fa-forward-fast"></i></a></li>
     {% else %}
     <li class="page-item"><a class="page-link disabled">Next </a></li>
     {% endif %}
    </ul>
</nav>

{% else %}
<p class="text-success">No users found.</p>
{% endif %}

{% endblock content %}

templates/landing_page.html
{% extends 'base.html' %}

{% block title %} Goodreads | Landing Page {% endblock title %}
{% block additional_styles %}
<style>
    body{
        background-image: linear-gradient( 102.4deg,  rgba(253,189,85,1) 7.8%, rgba(249,131,255,1) 100.3% );
    }
</style>
{% endblock additional_styles %}
{% load static %}
{% block content %}
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'assets/slide1.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Bu dasrtur ingliz tilidagi kitob muhokamasi uchun.</h5>
            <p>Biz kitoblar joylab boramiz . Kitoblar sahifasiga o'tib yoqtirgan kitobingizga izoh yozing !...</p>
          </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'assets/slide2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Kitoblar dunyoqarashingiz va shaxsiy rvojlanishingiz uchun eng yaxshi yo'ldir.</h5>
            <p> Kelgusida ingliz tilida sms yozishmalar , shaxsiy kabinet va video , audio muloqot xizmatlari ham yo'lga qo'yiladi. </p>
          </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'assets/slide3.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
            <h5>Ro'yxatdan o'ting va bepul aqliy saloyihatingizni rivojlantiring.</h5>
            <p>Chalg'ituvchi hayotda har narsaga chalg'imang vaqtingizni kitobxonlar orasida ham o'tkizing !...</p>
          </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock content %}